import { z } from 'zod';

// ============================================================================
// ADMIN CONSOLE — the shapes behind the /admin page: system health, request
// and login history, the log viewer, the endpoint catalogue and the database
// browser. Every route returning these is admin-only on the server.
// ============================================================================

export const HealthStatusEnum = z.enum(['up', 'degraded', 'down']);

export const HealthItemSchema = z.object({
    key: z.string(),
    label: z.string(),
    status: HealthStatusEnum,
    /** One plain-language line: a measurement, or the reason it is not healthy. */
    detail: z.string(),
});

/** One hour of API traffic. `hour` is the start of the hour, ISO 8601 UTC. */
export const HourlyStatsSchema = z.object({
    hour: z.string(),
    requests: z.number(),
    clientErrors: z.number(),
    serverErrors: z.number(),
    avgLatencyMs: z.number(),
    logins: z.number(),
    failedLogins: z.number(),
});

export const RouteStatsSchema = z.object({
    route: z.string(),
    count: z.number(),
    errors: z.number(),
    avgLatencyMs: z.number(),
});

export const TableSizeSchema = z.object({
    name: z.string(),
    bytes: z.number(),
    rows: z.number(),
});

export const AdminOverviewSchema = z.object({
    generatedAt: z.string(),
    uptimeSeconds: z.number(),
    nodeVersion: z.string(),
    environment: z.string(),
    aiEnabled: z.boolean(),
    health: z.array(HealthItemSchema),
    /** False when Redis is down: the traffic history below is then empty rather than wrong. */
    metricsAvailable: z.boolean(),
    hours: z.array(HourlyStatsSchema),
    topRoutes: z.array(RouteStatsSchema),
    databaseBytes: z.number(),
    tables: z.array(TableSizeSchema),
    usersByRole: z.array(z.object({ role: z.string(), count: z.number() })),
    activeUsers: z.number(),
    errorsByKind: z.array(z.object({ kind: z.string(), count: z.number() })),
});

export const LogLevelEnum = z.enum(['trace', 'debug', 'info', 'warn', 'error', 'fatal']);

export const AdminLogEntrySchema = z.object({
    id: z.number(),
    /** Epoch milliseconds. */
    time: z.number(),
    level: LogLevelEnum,
    message: z.string(),
    context: z.string().nullable(),
    method: z.string().nullable(),
    url: z.string().nullable(),
    status: z.number().nullable(),
    responseTimeMs: z.number().nullable(),
    /** Everything else pino recorded on the line, for the expanded view. */
    extra: z.record(z.string(), z.unknown()),
});

export const AdminLogsResponseSchema = z.object({
    entries: z.array(AdminLogEntrySchema),
    capacity: z.number(),
});

export const AuditEntrySchema = z.object({
    at: z.string(),
    user: z.string(),
    action: z.string(),
    detail: z.string(),
});

export const AuditLogResponseSchema = z.object({
    entries: z.array(AuditEntrySchema),
    persisted: z.boolean(),
});

export const ApiEndpointParameterSchema = z.object({
    name: z.string(),
    in: z.enum(['path', 'query', 'header']),
    required: z.boolean(),
    type: z.string(),
    options: z.array(z.string()).optional(),
    description: z.string().optional(),
});

export const ApiEndpointSchema = z.object({
    method: z.enum(['GET', 'POST', 'PUT', 'PATCH', 'DELETE']),
    path: z.string(),
    summary: z.string(),
    description: z.string().optional(),
    tag: z.string(),
    requiresAuth: z.boolean(),
    parameters: z.array(ApiEndpointParameterSchema),
    /** A starter JSON body built from the request schema; null when the route takes none. */
    bodyExample: z.unknown().nullable(),
});

export const ApiCatalogueSchema = z.object({
    endpoints: z.array(ApiEndpointSchema),
});

export const DbColumnSchema = z.object({
    name: z.string(),
    type: z.string(),
    nullable: z.boolean(),
    hasDefault: z.boolean(),
    isPrimaryKey: z.boolean(),
    /** Generated by the database, or never shown at all — cannot be set from the browser. */
    readOnly: z.boolean(),
    /** The allowed values when the column is a Postgres enum. */
    enumValues: z.array(z.string()).optional(),
});

export const DbTableSummarySchema = z.object({
    name: z.string(),
    rows: z.number(),
    bytes: z.number(),
    writable: z.boolean(),
});

export const DbTablesResponseSchema = z.object({
    tables: z.array(DbTableSummarySchema),
});

export const DbRowsResponseSchema = z.object({
    table: z.string(),
    writable: z.boolean(),
    columns: z.array(DbColumnSchema),
    rows: z.array(z.record(z.string(), z.unknown())),
    total: z.number(),
    page: z.number(),
    pageSize: z.number(),
});

const DbValueSchema = z.union([z.string(), z.number(), z.boolean(), z.null(), z.record(z.string(), z.unknown()), z.array(z.unknown())]);

export const DbInsertRequestSchema = z.object({
    values: z.record(z.string(), DbValueSchema),
});

export const DbUpdateRequestSchema = z.object({
    /** The row's primary-key column(s) and current value(s). */
    key: z.record(z.string(), z.union([z.string(), z.number()])),
    values: z.record(z.string(), DbValueSchema),
});

export const DbDeleteRequestSchema = z.object({
    key: z.record(z.string(), z.union([z.string(), z.number()])),
});

export const DbRowResponseSchema = z.object({
    row: z.record(z.string(), z.unknown()),
});

export type HealthStatus = z.infer<typeof HealthStatusEnum>;
export type HealthItem = z.infer<typeof HealthItemSchema>;
export type HourlyStats = z.infer<typeof HourlyStatsSchema>;
export type RouteStats = z.infer<typeof RouteStatsSchema>;
export type AdminOverview = z.infer<typeof AdminOverviewSchema>;
export type LogLevel = z.infer<typeof LogLevelEnum>;
export type AdminLogEntry = z.infer<typeof AdminLogEntrySchema>;
export type AuditEntry = z.infer<typeof AuditEntrySchema>;
export type ApiEndpoint = z.infer<typeof ApiEndpointSchema>;
export type ApiEndpointParameter = z.infer<typeof ApiEndpointParameterSchema>;
export type DbColumn = z.infer<typeof DbColumnSchema>;
export type DbTableSummary = z.infer<typeof DbTableSummarySchema>;
export type DbRowsResponse = z.infer<typeof DbRowsResponseSchema>;
export type DbInsertRequest = z.infer<typeof DbInsertRequestSchema>;
export type DbUpdateRequest = z.infer<typeof DbUpdateRequestSchema>;
export type DbDeleteRequest = z.infer<typeof DbDeleteRequestSchema>;
