import {
    Activity,
    BarChart3,
    Bell,
    BookOpen,
    Bot,
    Boxes,
    Briefcase,
    Bug,
    Building2,
    CircleDot,
    ClipboardCheck,
    ClipboardCopy,
    Coins,
    CreditCard,
    Database,
    Euro,
    FlaskConical,
    Gauge,
    Gavel,
    Globe,
    HeartPulse,
    Info,
    Inbox,
    Landmark,
    LineChart,
    ListChecks,
    ListOrdered,
    MapPin,
    MessagesSquare,
    Network,
    Newspaper,
    PackageCheck,
    Rocket,
    Scale,
    Server,
    ShieldCheck,
    ShoppingCart,
    SlidersHorizontal,
    Snowflake,
    Table2,
    Target,
    TrendingUp,
    Truck,
    UserCheck,
    Waypoints,
    Wrench,
    Zap,
    type LucideIcon,
} from "lucide-react"

/** First match wins, so the more specific patterns come first. Anything unmatched gets a plain dot. */
const ICONS: [RegExp, LucideIcon][] = [
    [/prerequisites/i, ListChecks],
    [/ground rules/i, Scale],
    [/how to read/i, Info],
    [/architecture/i, Network],
    [/scaling triggers/i, Gauge],
    [/sequencing/i, ListOrdered],
    [/icebox/i, Snowflake],
    [/^PHASE/i, Rocket],
    [/core pricing/i, Coins],
    [/money/i, Euro],
    [/freshness|feed/i, Activity],
    [/table and ux/i, Table2],
    [/copy and message/i, ClipboardCopy],
    [/security/i, ShieldCheck],
    [/reliability/i, Server],
    [/multi-branch data/i, Building2],
    [/health and monitoring/i, HeartPulse],
    [/testing|ci and docs/i, FlaskConical],
    [/spot isolation/i, Target],
    [/defects|hardening/i, Bug],
    [/market-data|market data flow/i, Waypoints],
    [/refactor/i, Wrench],
    [/desk tools/i, Briefcase],
    [/admin and management/i, SlidersHorizontal],
    [/historic spot|analytics/i, LineChart],
    [/knowledge/i, BookOpen],
    [/\bai agent|assistant/i, Bot],
    [/inquiry/i, Inbox],
    [/funds-landed/i, Landmark],
    [/hedge/i, Scale],
    [/audit/i, ClipboardCheck],
    [/alerts|limit orders/i, Bell],
    [/collections board/i, PackageCheck],
    [/inventory/i, Boxes],
    [/teams/i, MessagesSquare],
    [/news/i, Newspaper],
    [/zoho/i, Database],
    [/dashboards|kpi/i, BarChart3],
    [/compliance/i, Gavel],
    [/rollout/i, Rocket],
    [/public site/i, Globe],
    [/accounts and kyc/i, UserCheck],
    [/portal/i, UserCheck],
    [/cart|checkout/i, ShoppingCart],
    [/payment/i, CreditCard],
    [/auto-hedge/i, Zap],
    [/fulfilment/i, Truck],
    [/collection and delivery/i, MapPin],
    [/retention/i, UserCheck],
    [/pricing intelligence|growth|scale-up/i, TrendingUp],
]

export function sectionIcon(title: string): LucideIcon {
    return ICONS.find(([pattern]) => pattern.test(title))?.[1] ?? CircleDot
}
